# Generated by Django 3.1.7 on 2021-03-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase')], max_length=40)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.account')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EntryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductEntry.productentry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Product.product')),
            ],
        ),
    ]
