# Generated by Django 3.1.7 on 2021-06-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210525_1350'),
        ('ProductEntry', '0004_productentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryitem',
            name='weight',
        ),
        migrations.AddField(
            model_name='entryitem',
            name='quantity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Product.packing'),
            preserve_default=False,
        ),
    ]
