# Generated by Django 3.1.7 on 2021-06-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210525_1350'),
        ('ProductEntry', '0005_auto_20210605_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryitem',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Product.packing'),
        ),
        migrations.AlterField(
            model_name='entryitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
