# Generated by Django 3.1.7 on 2021-04-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=40)),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.account')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
