# Generated by Django 3.1.7 on 2021-04-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralEntry', '0002_generalentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalentry',
            name='user',
        ),
    ]
