# Generated by Django 3.1.7 on 2021-04-03 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GeneralEntry', '0003_remove_generalentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
